export const CONSTANTS = {
  BASE_URL: "https://localhost:7080/api",
  TOKEN: "token",
  AUTHENTICATED: "authenticated",
  TRUE: true,
  FALSE: "false",
  USERNAME: "username",
  ROLE: "role",
  CONTROLLER: {
    HOME: "/",
    LOGIN_PAGE: "/login",
    EXPENSE_LIST: "/expenselist",
    EXPENSE_FORM: "/expenseform",
    ADMIN_REPORTS: "/adminreports",
    ACCOUNTANT_PAYMENT: "/accountantpayment",
    MANAGER_APPROVAL: "/managerapproval",
    EXPENSE_HISTORY: "/expensehistory",
    ADMIN_EXPENSE_FORMS: "/adminexpenseforms",
    ADMIN_USERS: "/adminusers",
    ADMIN_UPDATE_MANAGER: "/adminupdatemanager",
    LOGIN: "/Authentication/login-user",
    REGISTER: "/Authentication/register-user",
    GET_EXPENSES: "/Employee/get-expense-form",
    UPDATE_EXPENSES: "/Employee/update-expense-form",
    ADD_EXPENSES: "/Employee/add-expense-form",
    GET_EXPENSES_MANAGER: "/Manager/get-expense-form",
    GET_EXPENSES_ACCOUNTANT: "/Accountant/get-expense-form",
    UPDATE_EXPENSE_MANAGER: "/Manager/update-expense-form",
    PAID_ACCOUNTANT: "/Accountant/pay-expense-form",
    ADMIN_API_EXPENSE_HISTORY: "/Admin/expense-history",
    ADMIN_API_EXPENSE_FORMS: "/Admin/expense-forms",
    ADMIN_API_USERS: "/Admin/users",
    ADMIN_API_UPDATE_MANAGER: "/Admin/update-managerid",
  },
};
